
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://123.57.178.76:3306/zt_shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: root@209
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 80

mybatis:
  mapper-locations: classpath*:mapper/*.xml